// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: contract/contract_pki_service.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PkiSignatureType int32

const (
	PkiSignatureType_UNKNOWN             PkiSignatureType = 0
	PkiSignatureType_CADES_BES           PkiSignatureType = 1
	PkiSignatureType_CADES_X_LONG_TYPE_1 PkiSignatureType = 2
	PkiSignatureType_CADES_T             PkiSignatureType = 3
)

// Enum value maps for PkiSignatureType.
var (
	PkiSignatureType_name = map[int32]string{
		0: "UNKNOWN",
		1: "CADES_BES",
		2: "CADES_X_LONG_TYPE_1",
		3: "CADES_T",
	}
	PkiSignatureType_value = map[string]int32{
		"UNKNOWN":             0,
		"CADES_BES":           1,
		"CADES_X_LONG_TYPE_1": 2,
		"CADES_T":             3,
	}
)

func (x PkiSignatureType) Enum() *PkiSignatureType {
	p := new(PkiSignatureType)
	*p = x
	return p
}

func (x PkiSignatureType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PkiSignatureType) Descriptor() protoreflect.EnumDescriptor {
	return file_contract_contract_pki_service_proto_enumTypes[0].Descriptor()
}

func (PkiSignatureType) Type() protoreflect.EnumType {
	return &file_contract_contract_pki_service_proto_enumTypes[0]
}

func (x PkiSignatureType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PkiSignatureType.Descriptor instead.
func (PkiSignatureType) EnumDescriptor() ([]byte, []int) {
	return file_contract_contract_pki_service_proto_rawDescGZIP(), []int{0}
}

type PkiVerifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputData            []byte           `protobuf:"bytes,1,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`
	Signature            []byte           `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	SigType              PkiSignatureType `protobuf:"varint,3,opt,name=sig_type,json=sigType,proto3,enum=wavesenterprise.PkiSignatureType" json:"sig_type,omitempty"`
	ExtendedKeyUsageList []string         `protobuf:"bytes,4,rep,name=extended_key_usage_list,json=extendedKeyUsageList,proto3" json:"extended_key_usage_list,omitempty"`
}

func (x *PkiVerifyRequest) Reset() {
	*x = PkiVerifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_contract_pki_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PkiVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PkiVerifyRequest) ProtoMessage() {}

func (x *PkiVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_pki_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PkiVerifyRequest.ProtoReflect.Descriptor instead.
func (*PkiVerifyRequest) Descriptor() ([]byte, []int) {
	return file_contract_contract_pki_service_proto_rawDescGZIP(), []int{0}
}

func (x *PkiVerifyRequest) GetInputData() []byte {
	if x != nil {
		return x.InputData
	}
	return nil
}

func (x *PkiVerifyRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *PkiVerifyRequest) GetSigType() PkiSignatureType {
	if x != nil {
		return x.SigType
	}
	return PkiSignatureType_UNKNOWN
}

func (x *PkiVerifyRequest) GetExtendedKeyUsageList() []string {
	if x != nil {
		return x.ExtendedKeyUsageList
	}
	return nil
}

type PkiVerifyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *PkiVerifyResponse) Reset() {
	*x = PkiVerifyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_contract_pki_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PkiVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PkiVerifyResponse) ProtoMessage() {}

func (x *PkiVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_pki_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PkiVerifyResponse.ProtoReflect.Descriptor instead.
func (*PkiVerifyResponse) Descriptor() ([]byte, []int) {
	return file_contract_contract_pki_service_proto_rawDescGZIP(), []int{1}
}

func (x *PkiVerifyResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_contract_contract_pki_service_proto protoreflect.FileDescriptor

var file_contract_contract_pki_service_proto_rawDesc = []byte{
	0x0a, 0x23, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x5f, 0x70, 0x6b, 0x69, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x77, 0x61, 0x76, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc4, 0x01, 0x0a, 0x10, 0x50, 0x6b, 0x69, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x3c, 0x0a, 0x08, 0x73, 0x69, 0x67, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x77, 0x61, 0x76,
	0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2e, 0x50, 0x6b, 0x69,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x73,
	0x69, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x35, 0x0a, 0x17, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64,
	0x65, 0x64, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x14, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65,
	0x64, 0x4b, 0x65, 0x79, 0x55, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x2b, 0x0a,
	0x11, 0x50, 0x6b, 0x69, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x54, 0x0a, 0x10, 0x50, 0x6b,
	0x69, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43,
	0x41, 0x44, 0x45, 0x53, 0x5f, 0x42, 0x45, 0x53, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x41,
	0x44, 0x45, 0x53, 0x5f, 0x58, 0x5f, 0x4c, 0x4f, 0x4e, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x31, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x41, 0x44, 0x45, 0x53, 0x5f, 0x54, 0x10, 0x03,
	0x32, 0x5d, 0x0a, 0x0a, 0x50, 0x6b, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f,
	0x0a, 0x06, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x21, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2e, 0x50, 0x6b, 0x69, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x77, 0x61,
	0x76, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2e, 0x50, 0x6b,
	0x69, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x5b, 0x0a, 0x2d, 0x63, 0x6f, 0x6d, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x50, 0x01, 0x5a, 0x16, 0x77, 0x65, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0xaa, 0x02, 0x0f, 0x57, 0x61, 0x76,
	0x65, 0x73, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_contract_contract_pki_service_proto_rawDescOnce sync.Once
	file_contract_contract_pki_service_proto_rawDescData = file_contract_contract_pki_service_proto_rawDesc
)

func file_contract_contract_pki_service_proto_rawDescGZIP() []byte {
	file_contract_contract_pki_service_proto_rawDescOnce.Do(func() {
		file_contract_contract_pki_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_contract_contract_pki_service_proto_rawDescData)
	})
	return file_contract_contract_pki_service_proto_rawDescData
}

var file_contract_contract_pki_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contract_contract_pki_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contract_contract_pki_service_proto_goTypes = []interface{}{
	(PkiSignatureType)(0),     // 0: wavesenterprise.PkiSignatureType
	(*PkiVerifyRequest)(nil),  // 1: wavesenterprise.PkiVerifyRequest
	(*PkiVerifyResponse)(nil), // 2: wavesenterprise.PkiVerifyResponse
}
var file_contract_contract_pki_service_proto_depIdxs = []int32{
	0, // 0: wavesenterprise.PkiVerifyRequest.sig_type:type_name -> wavesenterprise.PkiSignatureType
	1, // 1: wavesenterprise.PkiService.Verify:input_type -> wavesenterprise.PkiVerifyRequest
	2, // 2: wavesenterprise.PkiService.Verify:output_type -> wavesenterprise.PkiVerifyResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_contract_contract_pki_service_proto_init() }
func file_contract_contract_pki_service_proto_init() {
	if File_contract_contract_pki_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contract_contract_pki_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PkiVerifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_contract_pki_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PkiVerifyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contract_contract_pki_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_contract_pki_service_proto_goTypes,
		DependencyIndexes: file_contract_contract_pki_service_proto_depIdxs,
		EnumInfos:         file_contract_contract_pki_service_proto_enumTypes,
		MessageInfos:      file_contract_contract_pki_service_proto_msgTypes,
	}.Build()
	File_contract_contract_pki_service_proto = out.File
	file_contract_contract_pki_service_proto_rawDesc = nil
	file_contract_contract_pki_service_proto_goTypes = nil
	file_contract_contract_pki_service_proto_depIdxs = nil
}
