// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: contract/contract_privacy_service.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolicyRecipientsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyId string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
}

func (x *PolicyRecipientsRequest) Reset() {
	*x = PolicyRecipientsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_contract_privacy_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyRecipientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRecipientsRequest) ProtoMessage() {}

func (x *PolicyRecipientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_privacy_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRecipientsRequest.ProtoReflect.Descriptor instead.
func (*PolicyRecipientsRequest) Descriptor() ([]byte, []int) {
	return file_contract_contract_privacy_service_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyRecipientsRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type PolicyRecipientsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipients []string `protobuf:"bytes,1,rep,name=recipients,proto3" json:"recipients,omitempty"`
}

func (x *PolicyRecipientsResponse) Reset() {
	*x = PolicyRecipientsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_contract_privacy_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyRecipientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRecipientsResponse) ProtoMessage() {}

func (x *PolicyRecipientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_privacy_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRecipientsResponse.ProtoReflect.Descriptor instead.
func (*PolicyRecipientsResponse) Descriptor() ([]byte, []int) {
	return file_contract_contract_privacy_service_proto_rawDescGZIP(), []int{1}
}

func (x *PolicyRecipientsResponse) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

type PolicyOwnersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyId string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
}

func (x *PolicyOwnersRequest) Reset() {
	*x = PolicyOwnersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_contract_privacy_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyOwnersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyOwnersRequest) ProtoMessage() {}

func (x *PolicyOwnersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_privacy_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyOwnersRequest.ProtoReflect.Descriptor instead.
func (*PolicyOwnersRequest) Descriptor() ([]byte, []int) {
	return file_contract_contract_privacy_service_proto_rawDescGZIP(), []int{2}
}

func (x *PolicyOwnersRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type PolicyOwnersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owners []string `protobuf:"bytes,1,rep,name=owners,proto3" json:"owners,omitempty"`
}

func (x *PolicyOwnersResponse) Reset() {
	*x = PolicyOwnersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_contract_privacy_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyOwnersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyOwnersResponse) ProtoMessage() {}

func (x *PolicyOwnersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_privacy_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyOwnersResponse.ProtoReflect.Descriptor instead.
func (*PolicyOwnersResponse) Descriptor() ([]byte, []int) {
	return file_contract_contract_privacy_service_proto_rawDescGZIP(), []int{3}
}

func (x *PolicyOwnersResponse) GetOwners() []string {
	if x != nil {
		return x.Owners
	}
	return nil
}

type PolicyHashesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyId string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
}

func (x *PolicyHashesRequest) Reset() {
	*x = PolicyHashesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_contract_privacy_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyHashesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyHashesRequest) ProtoMessage() {}

func (x *PolicyHashesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_privacy_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyHashesRequest.ProtoReflect.Descriptor instead.
func (*PolicyHashesRequest) Descriptor() ([]byte, []int) {
	return file_contract_contract_privacy_service_proto_rawDescGZIP(), []int{4}
}

func (x *PolicyHashesRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type PolicyHashesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hashes []string `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
}

func (x *PolicyHashesResponse) Reset() {
	*x = PolicyHashesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_contract_privacy_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyHashesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyHashesResponse) ProtoMessage() {}

func (x *PolicyHashesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_privacy_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyHashesResponse.ProtoReflect.Descriptor instead.
func (*PolicyHashesResponse) Descriptor() ([]byte, []int) {
	return file_contract_contract_privacy_service_proto_rawDescGZIP(), []int{5}
}

func (x *PolicyHashesResponse) GetHashes() []string {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type PolicyItemDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyId string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	ItemHash string `protobuf:"bytes,2,opt,name=item_hash,json=itemHash,proto3" json:"item_hash,omitempty"`
}

func (x *PolicyItemDataRequest) Reset() {
	*x = PolicyItemDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_contract_privacy_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyItemDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyItemDataRequest) ProtoMessage() {}

func (x *PolicyItemDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_privacy_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyItemDataRequest.ProtoReflect.Descriptor instead.
func (*PolicyItemDataRequest) Descriptor() ([]byte, []int) {
	return file_contract_contract_privacy_service_proto_rawDescGZIP(), []int{6}
}

func (x *PolicyItemDataRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PolicyItemDataRequest) GetItemHash() string {
	if x != nil {
		return x.ItemHash
	}
	return ""
}

type PolicyItemDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PolicyItemDataResponse) Reset() {
	*x = PolicyItemDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_contract_privacy_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyItemDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyItemDataResponse) ProtoMessage() {}

func (x *PolicyItemDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_privacy_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyItemDataResponse.ProtoReflect.Descriptor instead.
func (*PolicyItemDataResponse) Descriptor() ([]byte, []int) {
	return file_contract_contract_privacy_service_proto_rawDescGZIP(), []int{7}
}

func (x *PolicyItemDataResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type PolicyItemInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyId string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	ItemHash string `protobuf:"bytes,2,opt,name=item_hash,json=itemHash,proto3" json:"item_hash,omitempty"`
}

func (x *PolicyItemInfoRequest) Reset() {
	*x = PolicyItemInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_contract_privacy_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyItemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyItemInfoRequest) ProtoMessage() {}

func (x *PolicyItemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_privacy_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyItemInfoRequest.ProtoReflect.Descriptor instead.
func (*PolicyItemInfoRequest) Descriptor() ([]byte, []int) {
	return file_contract_contract_privacy_service_proto_rawDescGZIP(), []int{8}
}

func (x *PolicyItemInfoRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PolicyItemInfoRequest) GetItemHash() string {
	if x != nil {
		return x.ItemHash
	}
	return ""
}

type PolicyItemInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender   string              `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	PolicyId string              `protobuf:"bytes,2,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Type     string              `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Info     *PolicyItemFileInfo `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	Hash     string              `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *PolicyItemInfoResponse) Reset() {
	*x = PolicyItemInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_contract_privacy_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyItemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyItemInfoResponse) ProtoMessage() {}

func (x *PolicyItemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_privacy_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyItemInfoResponse.ProtoReflect.Descriptor instead.
func (*PolicyItemInfoResponse) Descriptor() ([]byte, []int) {
	return file_contract_contract_privacy_service_proto_rawDescGZIP(), []int{9}
}

func (x *PolicyItemInfoResponse) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *PolicyItemInfoResponse) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PolicyItemInfoResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PolicyItemInfoResponse) GetInfo() *PolicyItemFileInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *PolicyItemInfoResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type PolicyItemFileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename  string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Size      int32  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Timestamp int64  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Author    string `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Comment   string `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *PolicyItemFileInfo) Reset() {
	*x = PolicyItemFileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contract_contract_privacy_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyItemFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyItemFileInfo) ProtoMessage() {}

func (x *PolicyItemFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_privacy_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyItemFileInfo.ProtoReflect.Descriptor instead.
func (*PolicyItemFileInfo) Descriptor() ([]byte, []int) {
	return file_contract_contract_privacy_service_proto_rawDescGZIP(), []int{10}
}

func (x *PolicyItemFileInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *PolicyItemFileInfo) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PolicyItemFileInfo) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PolicyItemFileInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PolicyItemFileInfo) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

var File_contract_contract_privacy_service_proto protoreflect.FileDescriptor

var file_contract_contract_privacy_service_proto_rawDesc = []byte{
	0x0a, 0x27, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x77, 0x61, 0x76, 0x65, 0x73,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x22, 0x36, 0x0a, 0x17, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x49, 0x64, 0x22, 0x3a, 0x0a, 0x18, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x63, 0x69,
	0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x32,
	0x0a, 0x13, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x49, 0x64, 0x22, 0x2e, 0x0a, 0x14, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x73, 0x22, 0x32, 0x0a, 0x13, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x48, 0x61, 0x73, 0x68,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x14, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x68, 0x61, 0x73, 0x68, 0x65, 0x73, 0x22, 0x51, 0x0a, 0x15, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x49, 0x74, 0x65, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x69, 0x74, 0x65, 0x6d, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x69, 0x74, 0x65, 0x6d, 0x48, 0x61, 0x73, 0x68, 0x22, 0x2c, 0x0a, 0x16, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x51, 0x0a, 0x15, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x48, 0x61, 0x73, 0x68, 0x22, 0xae, 0x01, 0x0a, 0x16, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1b, 0x0a,
	0x09, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x37,
	0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x77,
	0x61, 0x76, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2e, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x94, 0x01, 0x0a, 0x12,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x32, 0x88, 0x04, 0x0a, 0x0e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6a, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x28, 0x2e, 0x77,
	0x61, 0x76, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2e, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52,
	0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x5e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x73, 0x12, 0x24, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4f, 0x77, 0x6e,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x77, 0x61, 0x76,
	0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2e, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x5e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x48, 0x61,
	0x73, 0x68, 0x65, 0x73, 0x12, 0x24, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x48, 0x61, 0x73,
	0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x77, 0x61, 0x76,
	0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2e, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x64, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x74,
	0x65, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x26, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49,
	0x74, 0x65, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27,
	0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65,
	0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x2e, 0x77,
	0x61, 0x76, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2e, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x74, 0x65,
	0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x5b, 0x0a,
	0x2d, 0x63, 0x6f, 0x6d, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70,
	0x72, 0x69, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x50, 0x01,
	0x5a, 0x16, 0x77, 0x65, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0xaa, 0x02, 0x0f, 0x57, 0x61, 0x76, 0x65, 0x73,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_contract_contract_privacy_service_proto_rawDescOnce sync.Once
	file_contract_contract_privacy_service_proto_rawDescData = file_contract_contract_privacy_service_proto_rawDesc
)

func file_contract_contract_privacy_service_proto_rawDescGZIP() []byte {
	file_contract_contract_privacy_service_proto_rawDescOnce.Do(func() {
		file_contract_contract_privacy_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_contract_contract_privacy_service_proto_rawDescData)
	})
	return file_contract_contract_privacy_service_proto_rawDescData
}

var file_contract_contract_privacy_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_contract_contract_privacy_service_proto_goTypes = []interface{}{
	(*PolicyRecipientsRequest)(nil),  // 0: wavesenterprise.PolicyRecipientsRequest
	(*PolicyRecipientsResponse)(nil), // 1: wavesenterprise.PolicyRecipientsResponse
	(*PolicyOwnersRequest)(nil),      // 2: wavesenterprise.PolicyOwnersRequest
	(*PolicyOwnersResponse)(nil),     // 3: wavesenterprise.PolicyOwnersResponse
	(*PolicyHashesRequest)(nil),      // 4: wavesenterprise.PolicyHashesRequest
	(*PolicyHashesResponse)(nil),     // 5: wavesenterprise.PolicyHashesResponse
	(*PolicyItemDataRequest)(nil),    // 6: wavesenterprise.PolicyItemDataRequest
	(*PolicyItemDataResponse)(nil),   // 7: wavesenterprise.PolicyItemDataResponse
	(*PolicyItemInfoRequest)(nil),    // 8: wavesenterprise.PolicyItemInfoRequest
	(*PolicyItemInfoResponse)(nil),   // 9: wavesenterprise.PolicyItemInfoResponse
	(*PolicyItemFileInfo)(nil),       // 10: wavesenterprise.PolicyItemFileInfo
}
var file_contract_contract_privacy_service_proto_depIdxs = []int32{
	10, // 0: wavesenterprise.PolicyItemInfoResponse.info:type_name -> wavesenterprise.PolicyItemFileInfo
	0,  // 1: wavesenterprise.PrivacyService.GetPolicyRecipients:input_type -> wavesenterprise.PolicyRecipientsRequest
	2,  // 2: wavesenterprise.PrivacyService.GetPolicyOwners:input_type -> wavesenterprise.PolicyOwnersRequest
	4,  // 3: wavesenterprise.PrivacyService.GetPolicyHashes:input_type -> wavesenterprise.PolicyHashesRequest
	6,  // 4: wavesenterprise.PrivacyService.GetPolicyItemData:input_type -> wavesenterprise.PolicyItemDataRequest
	8,  // 5: wavesenterprise.PrivacyService.GetPolicyItemInfo:input_type -> wavesenterprise.PolicyItemInfoRequest
	1,  // 6: wavesenterprise.PrivacyService.GetPolicyRecipients:output_type -> wavesenterprise.PolicyRecipientsResponse
	3,  // 7: wavesenterprise.PrivacyService.GetPolicyOwners:output_type -> wavesenterprise.PolicyOwnersResponse
	5,  // 8: wavesenterprise.PrivacyService.GetPolicyHashes:output_type -> wavesenterprise.PolicyHashesResponse
	7,  // 9: wavesenterprise.PrivacyService.GetPolicyItemData:output_type -> wavesenterprise.PolicyItemDataResponse
	9,  // 10: wavesenterprise.PrivacyService.GetPolicyItemInfo:output_type -> wavesenterprise.PolicyItemInfoResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_contract_contract_privacy_service_proto_init() }
func file_contract_contract_privacy_service_proto_init() {
	if File_contract_contract_privacy_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contract_contract_privacy_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyRecipientsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_contract_privacy_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyRecipientsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_contract_privacy_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyOwnersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_contract_privacy_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyOwnersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_contract_privacy_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyHashesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_contract_privacy_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyHashesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_contract_privacy_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyItemDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_contract_privacy_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyItemDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_contract_privacy_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyItemInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_contract_privacy_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyItemInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contract_contract_privacy_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyItemFileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contract_contract_privacy_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_contract_privacy_service_proto_goTypes,
		DependencyIndexes: file_contract_contract_privacy_service_proto_depIdxs,
		MessageInfos:      file_contract_contract_privacy_service_proto_msgTypes,
	}.Build()
	File_contract_contract_privacy_service_proto = out.File
	file_contract_contract_privacy_service_proto_rawDesc = nil
	file_contract_contract_privacy_service_proto_goTypes = nil
	file_contract_contract_privacy_service_proto_depIdxs = nil
}
