// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: contract/contract_pki_service.proto

package contract

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PkiServiceClient is the client API for PkiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PkiServiceClient interface {
	Verify(ctx context.Context, in *PkiVerifyRequest, opts ...grpc.CallOption) (*PkiVerifyResponse, error)
}

type pkiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPkiServiceClient(cc grpc.ClientConnInterface) PkiServiceClient {
	return &pkiServiceClient{cc}
}

func (c *pkiServiceClient) Verify(ctx context.Context, in *PkiVerifyRequest, opts ...grpc.CallOption) (*PkiVerifyResponse, error) {
	out := new(PkiVerifyResponse)
	err := c.cc.Invoke(ctx, "/wavesenterprise.PkiService/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PkiServiceServer is the server API for PkiService service.
// All implementations must embed UnimplementedPkiServiceServer
// for forward compatibility
type PkiServiceServer interface {
	Verify(context.Context, *PkiVerifyRequest) (*PkiVerifyResponse, error)
	mustEmbedUnimplementedPkiServiceServer()
}

// UnimplementedPkiServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPkiServiceServer struct {
}

func (UnimplementedPkiServiceServer) Verify(context.Context, *PkiVerifyRequest) (*PkiVerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedPkiServiceServer) mustEmbedUnimplementedPkiServiceServer() {}

// UnsafePkiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PkiServiceServer will
// result in compilation errors.
type UnsafePkiServiceServer interface {
	mustEmbedUnimplementedPkiServiceServer()
}

func RegisterPkiServiceServer(s grpc.ServiceRegistrar, srv PkiServiceServer) {
	s.RegisterService(&PkiService_ServiceDesc, srv)
}

func _PkiService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PkiVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PkiServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wavesenterprise.PkiService/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PkiServiceServer).Verify(ctx, req.(*PkiVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PkiService_ServiceDesc is the grpc.ServiceDesc for PkiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PkiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wavesenterprise.PkiService",
	HandlerType: (*PkiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Verify",
			Handler:    _PkiService_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contract/contract_pki_service.proto",
}
