// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: util/util_node_info_service.proto

package util

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NodeInfoServiceClient is the client API for NodeInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeInfoServiceClient interface {
	NodeConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NodeConfigResponse, error)
	NodeOwner(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AddressWithPubKeyResponse, error)
}

type nodeInfoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeInfoServiceClient(cc grpc.ClientConnInterface) NodeInfoServiceClient {
	return &nodeInfoServiceClient{cc}
}

func (c *nodeInfoServiceClient) NodeConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NodeConfigResponse, error) {
	out := new(NodeConfigResponse)
	err := c.cc.Invoke(ctx, "/wavesenterprise.NodeInfoService/NodeConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeInfoServiceClient) NodeOwner(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AddressWithPubKeyResponse, error) {
	out := new(AddressWithPubKeyResponse)
	err := c.cc.Invoke(ctx, "/wavesenterprise.NodeInfoService/NodeOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeInfoServiceServer is the server API for NodeInfoService service.
// All implementations must embed UnimplementedNodeInfoServiceServer
// for forward compatibility
type NodeInfoServiceServer interface {
	NodeConfig(context.Context, *emptypb.Empty) (*NodeConfigResponse, error)
	NodeOwner(context.Context, *emptypb.Empty) (*AddressWithPubKeyResponse, error)
	mustEmbedUnimplementedNodeInfoServiceServer()
}

// UnimplementedNodeInfoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNodeInfoServiceServer struct {
}

func (UnimplementedNodeInfoServiceServer) NodeConfig(context.Context, *emptypb.Empty) (*NodeConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeConfig not implemented")
}
func (UnimplementedNodeInfoServiceServer) NodeOwner(context.Context, *emptypb.Empty) (*AddressWithPubKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeOwner not implemented")
}
func (UnimplementedNodeInfoServiceServer) mustEmbedUnimplementedNodeInfoServiceServer() {}

// UnsafeNodeInfoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeInfoServiceServer will
// result in compilation errors.
type UnsafeNodeInfoServiceServer interface {
	mustEmbedUnimplementedNodeInfoServiceServer()
}

func RegisterNodeInfoServiceServer(s grpc.ServiceRegistrar, srv NodeInfoServiceServer) {
	s.RegisterService(&NodeInfoService_ServiceDesc, srv)
}

func _NodeInfoService_NodeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeInfoServiceServer).NodeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wavesenterprise.NodeInfoService/NodeConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeInfoServiceServer).NodeConfig(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeInfoService_NodeOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeInfoServiceServer).NodeOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wavesenterprise.NodeInfoService/NodeOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeInfoServiceServer).NodeOwner(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeInfoService_ServiceDesc is the grpc.ServiceDesc for NodeInfoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeInfoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wavesenterprise.NodeInfoService",
	HandlerType: (*NodeInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NodeConfig",
			Handler:    _NodeInfoService_NodeConfig_Handler,
		},
		{
			MethodName: "NodeOwner",
			Handler:    _NodeInfoService_NodeOwner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "util/util_node_info_service.proto",
}
