// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: constants.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CryptoAlgo int32

const (
	CryptoAlgo_UNKNOWN_CRYPTO_ALGO CryptoAlgo = 0
	CryptoAlgo_GOST_3412_2015_K    CryptoAlgo = 2
	CryptoAlgo_AES                 CryptoAlgo = 3
)

// Enum value maps for CryptoAlgo.
var (
	CryptoAlgo_name = map[int32]string{
		0: "UNKNOWN_CRYPTO_ALGO",
		2: "GOST_3412_2015_K",
		3: "AES",
	}
	CryptoAlgo_value = map[string]int32{
		"UNKNOWN_CRYPTO_ALGO": 0,
		"GOST_3412_2015_K":    2,
		"AES":                 3,
	}
)

func (x CryptoAlgo) Enum() *CryptoAlgo {
	p := new(CryptoAlgo)
	*p = x
	return p
}

func (x CryptoAlgo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CryptoAlgo) Descriptor() protoreflect.EnumDescriptor {
	return file_constants_proto_enumTypes[0].Descriptor()
}

func (CryptoAlgo) Type() protoreflect.EnumType {
	return &file_constants_proto_enumTypes[0]
}

func (x CryptoAlgo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CryptoAlgo.Descriptor instead.
func (CryptoAlgo) EnumDescriptor() ([]byte, []int) {
	return file_constants_proto_rawDescGZIP(), []int{0}
}

type CryptoType int32

const (
	CryptoType_UNKNOWN_CRYPTO_TYPE CryptoType = 0
	CryptoType_GOST                CryptoType = 1
	CryptoType_CURVE_25519         CryptoType = 2
)

// Enum value maps for CryptoType.
var (
	CryptoType_name = map[int32]string{
		0: "UNKNOWN_CRYPTO_TYPE",
		1: "GOST",
		2: "CURVE_25519",
	}
	CryptoType_value = map[string]int32{
		"UNKNOWN_CRYPTO_TYPE": 0,
		"GOST":                1,
		"CURVE_25519":         2,
	}
)

func (x CryptoType) Enum() *CryptoType {
	p := new(CryptoType)
	*p = x
	return p
}

func (x CryptoType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CryptoType) Descriptor() protoreflect.EnumDescriptor {
	return file_constants_proto_enumTypes[1].Descriptor()
}

func (CryptoType) Type() protoreflect.EnumType {
	return &file_constants_proto_enumTypes[1]
}

func (x CryptoType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CryptoType.Descriptor instead.
func (CryptoType) EnumDescriptor() ([]byte, []int) {
	return file_constants_proto_rawDescGZIP(), []int{1}
}

type ConsensusType int32

const (
	ConsensusType_UNKNOWN_CONSENSUS_TYPE ConsensusType = 0
	ConsensusType_POA                    ConsensusType = 1
	ConsensusType_POS                    ConsensusType = 2
	ConsensusType_CFT                    ConsensusType = 3
)

// Enum value maps for ConsensusType.
var (
	ConsensusType_name = map[int32]string{
		0: "UNKNOWN_CONSENSUS_TYPE",
		1: "POA",
		2: "POS",
		3: "CFT",
	}
	ConsensusType_value = map[string]int32{
		"UNKNOWN_CONSENSUS_TYPE": 0,
		"POA":                    1,
		"POS":                    2,
		"CFT":                    3,
	}
)

func (x ConsensusType) Enum() *ConsensusType {
	p := new(ConsensusType)
	*p = x
	return p
}

func (x ConsensusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsensusType) Descriptor() protoreflect.EnumDescriptor {
	return file_constants_proto_enumTypes[2].Descriptor()
}

func (ConsensusType) Type() protoreflect.EnumType {
	return &file_constants_proto_enumTypes[2]
}

func (x ConsensusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsensusType.Descriptor instead.
func (ConsensusType) EnumDescriptor() ([]byte, []int) {
	return file_constants_proto_rawDescGZIP(), []int{2}
}

type PkiMode int32

const (
	PkiMode_UNKNOWN_PKI_MODE PkiMode = 0
	PkiMode_ON               PkiMode = 1
	PkiMode_OFF              PkiMode = 2
	PkiMode_TEST             PkiMode = 3
)

// Enum value maps for PkiMode.
var (
	PkiMode_name = map[int32]string{
		0: "UNKNOWN_PKI_MODE",
		1: "ON",
		2: "OFF",
		3: "TEST",
	}
	PkiMode_value = map[string]int32{
		"UNKNOWN_PKI_MODE": 0,
		"ON":               1,
		"OFF":              2,
		"TEST":             3,
	}
)

func (x PkiMode) Enum() *PkiMode {
	p := new(PkiMode)
	*p = x
	return p
}

func (x PkiMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PkiMode) Descriptor() protoreflect.EnumDescriptor {
	return file_constants_proto_enumTypes[3].Descriptor()
}

func (PkiMode) Type() protoreflect.EnumType {
	return &file_constants_proto_enumTypes[3]
}

func (x PkiMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PkiMode.Descriptor instead.
func (PkiMode) EnumDescriptor() ([]byte, []int) {
	return file_constants_proto_rawDescGZIP(), []int{3}
}

var File_constants_proto protoreflect.FileDescriptor

var file_constants_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0f, 0x77, 0x61, 0x76, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69,
	0x73, 0x65, 0x2a, 0x4a, 0x0a, 0x0a, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x41, 0x6c, 0x67, 0x6f,
	0x12, 0x17, 0x0a, 0x13, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x43, 0x52, 0x59, 0x50,
	0x54, 0x4f, 0x5f, 0x41, 0x4c, 0x47, 0x4f, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x47, 0x4f, 0x53,
	0x54, 0x5f, 0x33, 0x34, 0x31, 0x32, 0x5f, 0x32, 0x30, 0x31, 0x35, 0x5f, 0x4b, 0x10, 0x02, 0x12,
	0x07, 0x0a, 0x03, 0x41, 0x45, 0x53, 0x10, 0x03, 0x22, 0x04, 0x08, 0x01, 0x10, 0x01, 0x2a, 0x40,
	0x0a, 0x0a, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x13,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x43, 0x52, 0x59, 0x50, 0x54, 0x4f, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x4f, 0x53, 0x54, 0x10, 0x01, 0x12,
	0x0f, 0x0a, 0x0b, 0x43, 0x55, 0x52, 0x56, 0x45, 0x5f, 0x32, 0x35, 0x35, 0x31, 0x39, 0x10, 0x02,
	0x2a, 0x46, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1a, 0x0a, 0x16, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x43, 0x4f, 0x4e,
	0x53, 0x45, 0x4e, 0x53, 0x55, 0x53, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x50, 0x4f, 0x41, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x4f, 0x53, 0x10, 0x02, 0x12,
	0x07, 0x0a, 0x03, 0x43, 0x46, 0x54, 0x10, 0x03, 0x2a, 0x3a, 0x0a, 0x07, 0x50, 0x6b, 0x69, 0x4d,
	0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x50,
	0x4b, 0x49, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4e, 0x10,
	0x01, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x46, 0x46, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45,
	0x53, 0x54, 0x10, 0x03, 0x42, 0x49, 0x0a, 0x26, 0x63, 0x6f, 0x6d, 0x2e, 0x77, 0x61, 0x76, 0x65,
	0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x73, 0x5a, 0x0d,
	0x77, 0x65, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0xaa, 0x02, 0x0f,
	0x57, 0x61, 0x76, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_constants_proto_rawDescOnce sync.Once
	file_constants_proto_rawDescData = file_constants_proto_rawDesc
)

func file_constants_proto_rawDescGZIP() []byte {
	file_constants_proto_rawDescOnce.Do(func() {
		file_constants_proto_rawDescData = protoimpl.X.CompressGZIP(file_constants_proto_rawDescData)
	})
	return file_constants_proto_rawDescData
}

var file_constants_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_constants_proto_goTypes = []interface{}{
	(CryptoAlgo)(0),    // 0: wavesenterprise.CryptoAlgo
	(CryptoType)(0),    // 1: wavesenterprise.CryptoType
	(ConsensusType)(0), // 2: wavesenterprise.ConsensusType
	(PkiMode)(0),       // 3: wavesenterprise.PkiMode
}
var file_constants_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_constants_proto_init() }
func file_constants_proto_init() {
	if File_constants_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_constants_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_constants_proto_goTypes,
		DependencyIndexes: file_constants_proto_depIdxs,
		EnumInfos:         file_constants_proto_enumTypes,
	}.Build()
	File_constants_proto = out.File
	file_constants_proto_rawDesc = nil
	file_constants_proto_goTypes = nil
	file_constants_proto_depIdxs = nil
}
