// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: data_entry.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are assignable to Value:
	//	*DataEntry_IntValue
	//	*DataEntry_BoolValue
	//	*DataEntry_BinaryValue
	//	*DataEntry_StringValue
	Value isDataEntry_Value `protobuf_oneof:"value"`
}

func (x *DataEntry) Reset() {
	*x = DataEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_entry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataEntry) ProtoMessage() {}

func (x *DataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_data_entry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataEntry.ProtoReflect.Descriptor instead.
func (*DataEntry) Descriptor() ([]byte, []int) {
	return file_data_entry_proto_rawDescGZIP(), []int{0}
}

func (x *DataEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (m *DataEntry) GetValue() isDataEntry_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *DataEntry) GetIntValue() int64 {
	if x, ok := x.GetValue().(*DataEntry_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (x *DataEntry) GetBoolValue() bool {
	if x, ok := x.GetValue().(*DataEntry_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (x *DataEntry) GetBinaryValue() []byte {
	if x, ok := x.GetValue().(*DataEntry_BinaryValue); ok {
		return x.BinaryValue
	}
	return nil
}

func (x *DataEntry) GetStringValue() string {
	if x, ok := x.GetValue().(*DataEntry_StringValue); ok {
		return x.StringValue
	}
	return ""
}

type isDataEntry_Value interface {
	isDataEntry_Value()
}

type DataEntry_IntValue struct {
	IntValue int64 `protobuf:"varint,10,opt,name=int_value,json=intValue,proto3,oneof"`
}

type DataEntry_BoolValue struct {
	BoolValue bool `protobuf:"varint,11,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type DataEntry_BinaryValue struct {
	BinaryValue []byte `protobuf:"bytes,12,opt,name=binary_value,json=binaryValue,proto3,oneof"`
}

type DataEntry_StringValue struct {
	StringValue string `protobuf:"bytes,13,opt,name=string_value,json=stringValue,proto3,oneof"`
}

func (*DataEntry_IntValue) isDataEntry_Value() {}

func (*DataEntry_BoolValue) isDataEntry_Value() {}

func (*DataEntry_BinaryValue) isDataEntry_Value() {}

func (*DataEntry_StringValue) isDataEntry_Value() {}

var File_data_entry_proto protoreflect.FileDescriptor

var file_data_entry_proto_rawDesc = []byte{
	0x0a, 0x10, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0f, 0x77, 0x61, 0x76, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72,
	0x69, 0x73, 0x65, 0x22, 0xb4, 0x01, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x42, 0x02, 0x30, 0x01, 0x48, 0x00, 0x52, 0x08, 0x69, 0x6e,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6f,
	0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x62, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52,
	0x0b, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x4d, 0x0a, 0x28, 0x63, 0x6f,
	0x6d, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73,
	0x65, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x50, 0x01, 0x5a, 0x0d, 0x77, 0x65, 0x67, 0x6f, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0xaa, 0x02, 0x0f, 0x57, 0x61, 0x76, 0x65, 0x73, 0x45,
	0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_data_entry_proto_rawDescOnce sync.Once
	file_data_entry_proto_rawDescData = file_data_entry_proto_rawDesc
)

func file_data_entry_proto_rawDescGZIP() []byte {
	file_data_entry_proto_rawDescOnce.Do(func() {
		file_data_entry_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_entry_proto_rawDescData)
	})
	return file_data_entry_proto_rawDescData
}

var file_data_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_data_entry_proto_goTypes = []interface{}{
	(*DataEntry)(nil), // 0: wavesenterprise.DataEntry
}
var file_data_entry_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_entry_proto_init() }
func file_data_entry_proto_init() {
	if File_data_entry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_entry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_data_entry_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*DataEntry_IntValue)(nil),
		(*DataEntry_BoolValue)(nil),
		(*DataEntry_BinaryValue)(nil),
		(*DataEntry_StringValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_entry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_entry_proto_goTypes,
		DependencyIndexes: file_data_entry_proto_depIdxs,
		MessageInfos:      file_data_entry_proto_msgTypes,
	}.Build()
	File_data_entry_proto = out.File
	file_data_entry_proto_rawDesc = nil
	file_data_entry_proto_goTypes = nil
	file_data_entry_proto_depIdxs = nil
}
