// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: op_type.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpType int32

const (
	OpType_UNKNOWN_OP_TYPE OpType = 0
	OpType_ADD             OpType = 1
	OpType_REMOVE          OpType = 2
)

// Enum value maps for OpType.
var (
	OpType_name = map[int32]string{
		0: "UNKNOWN_OP_TYPE",
		1: "ADD",
		2: "REMOVE",
	}
	OpType_value = map[string]int32{
		"UNKNOWN_OP_TYPE": 0,
		"ADD":             1,
		"REMOVE":          2,
	}
)

func (x OpType) Enum() *OpType {
	p := new(OpType)
	*p = x
	return p
}

func (x OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_op_type_proto_enumTypes[0].Descriptor()
}

func (OpType) Type() protoreflect.EnumType {
	return &file_op_type_proto_enumTypes[0]
}

func (x OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpType.Descriptor instead.
func (OpType) EnumDescriptor() ([]byte, []int) {
	return file_op_type_proto_rawDescGZIP(), []int{0}
}

var File_op_type_proto protoreflect.FileDescriptor

var file_op_type_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6f, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x77, 0x61, 0x76, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65,
	0x2a, 0x32, 0x0a, 0x06, 0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x4f, 0x50, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x00, 0x12,
	0x07, 0x0a, 0x03, 0x41, 0x44, 0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x4d, 0x4f,
	0x56, 0x45, 0x10, 0x02, 0x42, 0x4d, 0x0a, 0x28, 0x63, 0x6f, 0x6d, 0x2e, 0x77, 0x61, 0x76, 0x65,
	0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2e, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x50, 0x01, 0x5a, 0x0d, 0x77, 0x65, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0xaa, 0x02, 0x0f, 0x57, 0x61, 0x76, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72,
	0x69, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_op_type_proto_rawDescOnce sync.Once
	file_op_type_proto_rawDescData = file_op_type_proto_rawDesc
)

func file_op_type_proto_rawDescGZIP() []byte {
	file_op_type_proto_rawDescOnce.Do(func() {
		file_op_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_op_type_proto_rawDescData)
	})
	return file_op_type_proto_rawDescData
}

var file_op_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_op_type_proto_goTypes = []interface{}{
	(OpType)(0), // 0: wavesenterprise.OpType
}
var file_op_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_op_type_proto_init() }
func file_op_type_proto_init() {
	if File_op_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_op_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_op_type_proto_goTypes,
		DependencyIndexes: file_op_type_proto_depIdxs,
		EnumInfos:         file_op_type_proto_enumTypes,
	}.Build()
	File_op_type_proto = out.File
	file_op_type_proto_rawDesc = nil
	file_op_type_proto_goTypes = nil
	file_op_type_proto_depIdxs = nil
}
