// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: validation_policy.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidationPolicy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*ValidationPolicy_Any_
	//	*ValidationPolicy_Majority_
	//	*ValidationPolicy_MajorityWithOneOf_
	Type isValidationPolicy_Type `protobuf_oneof:"type"`
}

func (x *ValidationPolicy) Reset() {
	*x = ValidationPolicy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_validation_policy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidationPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationPolicy) ProtoMessage() {}

func (x *ValidationPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_validation_policy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationPolicy.ProtoReflect.Descriptor instead.
func (*ValidationPolicy) Descriptor() ([]byte, []int) {
	return file_validation_policy_proto_rawDescGZIP(), []int{0}
}

func (m *ValidationPolicy) GetType() isValidationPolicy_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *ValidationPolicy) GetAny() *ValidationPolicy_Any {
	if x, ok := x.GetType().(*ValidationPolicy_Any_); ok {
		return x.Any
	}
	return nil
}

func (x *ValidationPolicy) GetMajority() *ValidationPolicy_Majority {
	if x, ok := x.GetType().(*ValidationPolicy_Majority_); ok {
		return x.Majority
	}
	return nil
}

func (x *ValidationPolicy) GetMajorityWithOneOf() *ValidationPolicy_MajorityWithOneOf {
	if x, ok := x.GetType().(*ValidationPolicy_MajorityWithOneOf_); ok {
		return x.MajorityWithOneOf
	}
	return nil
}

type isValidationPolicy_Type interface {
	isValidationPolicy_Type()
}

type ValidationPolicy_Any_ struct {
	Any *ValidationPolicy_Any `protobuf:"bytes,10,opt,name=any,proto3,oneof"`
}

type ValidationPolicy_Majority_ struct {
	Majority *ValidationPolicy_Majority `protobuf:"bytes,11,opt,name=majority,proto3,oneof"`
}

type ValidationPolicy_MajorityWithOneOf_ struct {
	MajorityWithOneOf *ValidationPolicy_MajorityWithOneOf `protobuf:"bytes,12,opt,name=majority_with_one_of,json=majorityWithOneOf,proto3,oneof"`
}

func (*ValidationPolicy_Any_) isValidationPolicy_Type() {}

func (*ValidationPolicy_Majority_) isValidationPolicy_Type() {}

func (*ValidationPolicy_MajorityWithOneOf_) isValidationPolicy_Type() {}

type ValidationPolicy_Any struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ValidationPolicy_Any) Reset() {
	*x = ValidationPolicy_Any{}
	if protoimpl.UnsafeEnabled {
		mi := &file_validation_policy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidationPolicy_Any) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationPolicy_Any) ProtoMessage() {}

func (x *ValidationPolicy_Any) ProtoReflect() protoreflect.Message {
	mi := &file_validation_policy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationPolicy_Any.ProtoReflect.Descriptor instead.
func (*ValidationPolicy_Any) Descriptor() ([]byte, []int) {
	return file_validation_policy_proto_rawDescGZIP(), []int{0, 0}
}

type ValidationPolicy_Majority struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ValidationPolicy_Majority) Reset() {
	*x = ValidationPolicy_Majority{}
	if protoimpl.UnsafeEnabled {
		mi := &file_validation_policy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidationPolicy_Majority) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationPolicy_Majority) ProtoMessage() {}

func (x *ValidationPolicy_Majority) ProtoReflect() protoreflect.Message {
	mi := &file_validation_policy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationPolicy_Majority.ProtoReflect.Descriptor instead.
func (*ValidationPolicy_Majority) Descriptor() ([]byte, []int) {
	return file_validation_policy_proto_rawDescGZIP(), []int{0, 1}
}

type ValidationPolicy_MajorityWithOneOf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addresses [][]byte `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
}

func (x *ValidationPolicy_MajorityWithOneOf) Reset() {
	*x = ValidationPolicy_MajorityWithOneOf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_validation_policy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidationPolicy_MajorityWithOneOf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationPolicy_MajorityWithOneOf) ProtoMessage() {}

func (x *ValidationPolicy_MajorityWithOneOf) ProtoReflect() protoreflect.Message {
	mi := &file_validation_policy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationPolicy_MajorityWithOneOf.ProtoReflect.Descriptor instead.
func (*ValidationPolicy_MajorityWithOneOf) Descriptor() ([]byte, []int) {
	return file_validation_policy_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ValidationPolicy_MajorityWithOneOf) GetAddresses() [][]byte {
	if x != nil {
		return x.Addresses
	}
	return nil
}

var File_validation_policy_proto protoreflect.FileDescriptor

var file_validation_policy_proto_rawDesc = []byte{
	0x0a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x77, 0x61, 0x76, 0x65, 0x73,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x22, 0xcd, 0x02, 0x0a, 0x10, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12,
	0x39, 0x0a, 0x03, 0x61, 0x6e, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x77,
	0x61, 0x76, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2e, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e,
	0x41, 0x6e, 0x79, 0x48, 0x00, 0x52, 0x03, 0x61, 0x6e, 0x79, 0x12, 0x48, 0x0a, 0x08, 0x6d, 0x61,
	0x6a, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x77,
	0x61, 0x76, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2e, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e,
	0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x48, 0x00, 0x52, 0x08, 0x6d, 0x61, 0x6a, 0x6f,
	0x72, 0x69, 0x74, 0x79, 0x12, 0x66, 0x0a, 0x14, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x69, 0x74, 0x79,
	0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x6f, 0x6e, 0x65, 0x5f, 0x6f, 0x66, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x33, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70,
	0x72, 0x69, 0x73, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x57, 0x69,
	0x74, 0x68, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x48, 0x00, 0x52, 0x11, 0x6d, 0x61, 0x6a, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x1a, 0x05, 0x0a, 0x03,
	0x41, 0x6e, 0x79, 0x1a, 0x0a, 0x0a, 0x08, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x1a,
	0x31, 0x0a, 0x11, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x57, 0x69, 0x74, 0x68, 0x4f,
	0x6e, 0x65, 0x4f, 0x66, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x65, 0x73, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42, 0x4d, 0x0a, 0x28, 0x63, 0x6f,
	0x6d, 0x2e, 0x77, 0x61, 0x76, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73,
	0x65, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x50, 0x01, 0x5a, 0x0d, 0x77, 0x65, 0x67, 0x6f, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0xaa, 0x02, 0x0f, 0x57, 0x61, 0x76, 0x65, 0x73, 0x45,
	0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_validation_policy_proto_rawDescOnce sync.Once
	file_validation_policy_proto_rawDescData = file_validation_policy_proto_rawDesc
)

func file_validation_policy_proto_rawDescGZIP() []byte {
	file_validation_policy_proto_rawDescOnce.Do(func() {
		file_validation_policy_proto_rawDescData = protoimpl.X.CompressGZIP(file_validation_policy_proto_rawDescData)
	})
	return file_validation_policy_proto_rawDescData
}

var file_validation_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_validation_policy_proto_goTypes = []interface{}{
	(*ValidationPolicy)(nil),                   // 0: wavesenterprise.ValidationPolicy
	(*ValidationPolicy_Any)(nil),               // 1: wavesenterprise.ValidationPolicy.Any
	(*ValidationPolicy_Majority)(nil),          // 2: wavesenterprise.ValidationPolicy.Majority
	(*ValidationPolicy_MajorityWithOneOf)(nil), // 3: wavesenterprise.ValidationPolicy.MajorityWithOneOf
}
var file_validation_policy_proto_depIdxs = []int32{
	1, // 0: wavesenterprise.ValidationPolicy.any:type_name -> wavesenterprise.ValidationPolicy.Any
	2, // 1: wavesenterprise.ValidationPolicy.majority:type_name -> wavesenterprise.ValidationPolicy.Majority
	3, // 2: wavesenterprise.ValidationPolicy.majority_with_one_of:type_name -> wavesenterprise.ValidationPolicy.MajorityWithOneOf
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_validation_policy_proto_init() }
func file_validation_policy_proto_init() {
	if File_validation_policy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_validation_policy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidationPolicy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_validation_policy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidationPolicy_Any); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_validation_policy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidationPolicy_Majority); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_validation_policy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidationPolicy_MajorityWithOneOf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_validation_policy_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ValidationPolicy_Any_)(nil),
		(*ValidationPolicy_Majority_)(nil),
		(*ValidationPolicy_MajorityWithOneOf_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_validation_policy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_validation_policy_proto_goTypes,
		DependencyIndexes: file_validation_policy_proto_depIdxs,
		MessageInfos:      file_validation_policy_proto_msgTypes,
	}.Build()
	File_validation_policy_proto = out.File
	file_validation_policy_proto_rawDesc = nil
	file_validation_policy_proto_goTypes = nil
	file_validation_policy_proto_depIdxs = nil
}
