// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: genesis/genesis_permit_transaction.proto

package genesis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	grpc "wego/pkg/grpc"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenesisPermitTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        []byte     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Target    []byte     `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Role      *grpc.Role `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Fee       int64      `protobuf:"varint,4,opt,name=fee,proto3" json:"fee,omitempty"`
	Timestamp int64      `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature []byte     `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *GenesisPermitTransaction) Reset() {
	*x = GenesisPermitTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_genesis_genesis_permit_transaction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenesisPermitTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisPermitTransaction) ProtoMessage() {}

func (x *GenesisPermitTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_genesis_genesis_permit_transaction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisPermitTransaction.ProtoReflect.Descriptor instead.
func (*GenesisPermitTransaction) Descriptor() ([]byte, []int) {
	return file_genesis_genesis_permit_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *GenesisPermitTransaction) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GenesisPermitTransaction) GetTarget() []byte {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *GenesisPermitTransaction) GetRole() *grpc.Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *GenesisPermitTransaction) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *GenesisPermitTransaction) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GenesisPermitTransaction) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_genesis_genesis_permit_transaction_proto protoreflect.FileDescriptor

var file_genesis_genesis_permit_transaction_proto_rawDesc = []byte{
	0x0a, 0x28, 0x67, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x73, 0x69,
	0x73, 0x5f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x77, 0x61, 0x76, 0x65,
	0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x1a, 0x0a, 0x72, 0x6f, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbb, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x6e, 0x65,
	0x73, 0x69, 0x73, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x29, 0x0a, 0x04,
	0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x77, 0x61, 0x76,
	0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2e, 0x52, 0x6f, 0x6c,
	0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x66, 0x65, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x53, 0x0a, 0x28, 0x63, 0x6f, 0x6d, 0x2e, 0x77, 0x61, 0x76,
	0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x2e, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x5a, 0x15, 0x77, 0x65, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x67, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0xaa, 0x02, 0x0f, 0x57, 0x61, 0x76, 0x65, 0x73,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_genesis_genesis_permit_transaction_proto_rawDescOnce sync.Once
	file_genesis_genesis_permit_transaction_proto_rawDescData = file_genesis_genesis_permit_transaction_proto_rawDesc
)

func file_genesis_genesis_permit_transaction_proto_rawDescGZIP() []byte {
	file_genesis_genesis_permit_transaction_proto_rawDescOnce.Do(func() {
		file_genesis_genesis_permit_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_genesis_genesis_permit_transaction_proto_rawDescData)
	})
	return file_genesis_genesis_permit_transaction_proto_rawDescData
}

var file_genesis_genesis_permit_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_genesis_genesis_permit_transaction_proto_goTypes = []interface{}{
	(*GenesisPermitTransaction)(nil), // 0: wavesenterprise.GenesisPermitTransaction
	(*grpc.Role)(nil),                // 1: wavesenterprise.Role
}
var file_genesis_genesis_permit_transaction_proto_depIdxs = []int32{
	1, // 0: wavesenterprise.GenesisPermitTransaction.role:type_name -> wavesenterprise.Role
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_genesis_genesis_permit_transaction_proto_init() }
func file_genesis_genesis_permit_transaction_proto_init() {
	if File_genesis_genesis_permit_transaction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_genesis_genesis_permit_transaction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenesisPermitTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_genesis_genesis_permit_transaction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_genesis_genesis_permit_transaction_proto_goTypes,
		DependencyIndexes: file_genesis_genesis_permit_transaction_proto_depIdxs,
		MessageInfos:      file_genesis_genesis_permit_transaction_proto_msgTypes,
	}.Build()
	File_genesis_genesis_permit_transaction_proto = out.File
	file_genesis_genesis_permit_transaction_proto_rawDesc = nil
	file_genesis_genesis_permit_transaction_proto_goTypes = nil
	file_genesis_genesis_permit_transaction_proto_depIdxs = nil
}
